# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChallengeTV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChallengeTV
  # Image Processing
  pod 'SDWebImage', '~> 5.0'


  target 'ChallengeTVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChallengeTVUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SDWebImage', '~> 5.0'
  end

end
